// File icons from Material Icon Theme (MIT) — the set used by VS Code.
// Assets live in public/fileicons/ (generated by scripts/gen-file-icons.mjs).

import map from "./fileIconMap.json";

interface IconMap {
  file: string;
  folder: string;
  folderExpanded: string;
  fileNames: Record<string, string>;
  fileExtensions: Record<string, string>;
  folderNames: Record<string, string>;
  folderNamesExpanded: Record<string, string>;
}

const m = map as IconMap;

/** Resolve a file/folder name to an icon URL. */
export function fileIconSrc(name: string, kind: "file" | "dir" = "file", expanded = false): string {
  const lower = name.toLowerCase();
  let icon: string | undefined;

  if (kind === "dir") {
    icon = (expanded ? m.folderNamesExpanded[lower] : m.folderNames[lower]) ?? m.folderNames[lower] ?? m.folderNamesExpanded[lower];
    if (!icon) return `./fileicons/${expanded ? m.folderExpanded : m.folder}`;
  } else {
    icon = m.fileNames[lower];
    if (!icon) {
      // Longest extension match first ("blade.php" before "php"), like VS Code.
      const parts = lower.split(".");
      for (let i = 1; i < parts.length; i++) {
        const ext = parts.slice(i).join(".");
        if (m.fileExtensions[ext]) {
          icon = m.fileExtensions[ext];
          break;
        }
      }
    }
    if (!icon) return `./fileicons/${m.file}`;
  }
  return `./fileicons/${icon}`;
}
